language: php
php:
- 5.6
- 7.1
- 7.2
before_install:
- if [[ $TRAVIS_PHP_VERSION == 7.1* ]]; then composer require phpunit/phpunit:~6.0; else composer self-update;fi
before_script:
- composer install
script:
- phpunit --configuration phpunit.xml